env:
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Admin Builder"
  skip: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_USER_PERMISSION == 'admin'
  stateful: true
  timeout_in: 120m
  container:
    image: zacky46/ubuntu:22.04
    cpu: 8
    memory: 32G

  Check-User_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/checks.sh)"

  Load-Ccache_background_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/load_ccache.sh)"

  Sync-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/sync.sh)"
     
  Build-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/building.sh)"
     
  Ccache-info_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/ziping.sh)"
