env:
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "Admin Builder"
  skip: $CIRRUS_BRANCH == 'master'
  only_if: $CIRRUS_USER_PERMISSION == 'admin'
  stateful: true
  timeout_in: 120m
  container:
    image: ubuntu:22.04
    cpu: 8
    memory: 32G
    
  Build-Env-Setup_script:

       - export DEBIAN_FRONTEND=noninteractive

       - apt-get update

       - apt-get install sudo

       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata

       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

       - apt-get install -y tzdata

       - dpkg-reconfigure --frontend noninteractive tzdata

       - sudo apt-get update -y && sudo apt-get install git aria2 curl wget rsync zip unzip lzma cpio ccache clang -y

       - sudo apt-get install python3 -y

       - sudo ln -sf /usr/bin/python3 /usr/bin/python

       - git config --global user.name "Sushrut1101"

       - git config --global user.email "guptasushrut@gmail.com"

       - git clone https://github.com/akhilnarang/scripts.git ~/scripts

       - cd ~/scripts

       - sudo bash setup/android_build_env.sh

       - cd ~
       - mkdir -p ~/work

      - cd ~/work

      - mkdir -p ~/.bin

      - PATH="${HOME}/.bin:${PATH}"

      - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo

      - chmod a+rx ~/.bin/repo
  
  Check-User_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/checks.sh)"

  Load-Ccache_background_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/load_ccache.sh)"

  Sync-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/sync.sh)"
     
  Build-rom_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/building.sh)"
     
  Ccache-info_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - bash -c "$(curl -sL https://raw.githubusercontent.com/monu70152/rom/master/rom/ziping.sh)"
#end
